# Usamos la imagen oficial de Nginx
FROM nginx

# Copiamos los archivos del frontend a la carpeta donde Nginx los servirá
COPY . /usr/share/nginx/html

# Exponemos el puerto 80 para acceder al frontend
EXPOSE 80

