version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

