# 1️ Usamos la imagen base de Node.js (versión LTS)
FROM node:18-alpine

# 2 Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# 3️ Copiamos el package.json y package-lock.json al contenedor
COPY package*.json ./

# 4️ Instalamos las dependencias de Node.js
RUN npm install

# 5️ Copiamos el resto del código al contenedor
COPY . .

# 6️ Exponemos el puerto que usa el backend
EXPOSE 3000

# 7️ Comando para ejecutar el backend cuando el contenedor arranca
CMD ["node", "server.js"]

